### ISSUE TITLE
Support trio

### ISSUE THREAD

**Issue by kerizane** [python-trio/sniffio#15]
Docs say that trio can be detected, but that doesn't seem to be true.

**Comment by sethmlarson** [comment]
Can you provide the code you're running that's expecting Trio to be detected but isn't?

**Comment by kerizane** [comment]
Apologies, I just looked at the code. From googling I can see how it works.

https://sniffio.readthedocs.io/en/latest/#adding-support-to-a-new-async-library

Might be worth adding a comment and test coverage.
