### ISSUE TITLE
Test folder in test deliverable

### ISSUE THREAD

**Issue by guillaumeLepape** [python-trio/sniffio#41]
Hello, I just notice `_tests` folder is included in sniffio. I propose the following pr (https://github.com/python-trio/sniffio/pull/40) to fix it.

**Comment by A5rocks** [comment]
Oh sorry I didn't see this issue. We intentionally package the tests so that end users can run them too! Hopefully that makes sense?

**Comment by mcepl** [comment]
Please, don't stop putting those tests in the tarball (not in the wheel). Distributors (I work for SUSE on openSUSE among other things) like to run them.

**Comment by A5rocks** [comment]
Oh, I absolutely agree. I'm not sure why I didn't close it before, but I probably just wanted to get a response. Well, they can respond to a closed issue too!

**Comment by guillaumeLepape** [comment]
packaging the tests is not very standard and usually end users don't need to run their dependencies tests. But I guess there is nothing secret or heavy in the test suite.
I checked with the configuration is added, tests are not packaged anymore with both wheel and tar. But looks strange to run the tests contained in tar as most of python deliverable are not packaging the tests.

**Comment by mcepl** [comment]
On Fri Nov 17, 2023 at 4:43 PM CET, guillaumeLepape wrote:
> packaging the tests is not very standard and usually end users
> don't need to run their dependencies tests. But I guess there is
> nothing secret or heavy in the test suite.

Packaging of tests is VERY standard, we (openSUSE) have many
hundreds of Python packages where their tarball contains tests.

Normal users are not supposed to use tarballs, but for the mere
users of the package, there are always wheels, which certainly
should not contain it.

Best,

Matěj

-- 
http://matej.ceplovi.cz/blog/, @***@***.***
GPG Finger: 3C76 A027 CA45 AD70 98B5  BC1D 7920 5802 880B C9D8
 
If in desperation, read the documentation!
    -- Brian D. Ripley, on R-help list

**Comment by A5rocks** [comment]
I believe wheels too should contain tests and I know there are people who use `trio`'s packaged tests specifically from wheels (see https://github.com/python-trio/trio/issues/2863 for one case). While I don't know if anyone uses `sniffio`'s for a similar purpose, I certainly don't think drawing a distinction between packaging tests in sdists and wheels is worthwhile.
